require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 2.7

# メソッドの長さ
Metrics/MethodLength:
  Exclude:
    - "db/migrate/**/*"

# AbcSize
Metrics/AbcSize:
  Exclude:
    - "db/migrate/**/*"
    - "db/schema.rb"

# 行の長さ
Layout/LineLength:
  Exclude:
    - "config/initializers/**/*"

Metrics/BlockLength:
  Exclude:
    - "db/migrate/**/*"
    - "db/schema.rb"

Style/NumericLiterals:
  Exclude:
    - "db/schema.rb"

Style/BulkChangeTable:
  Exclude:
    - "db/migrate/**/*"
